# ====================================================================
# scripts/s65-pre-commit-setup.ps1
# ====================================================================
# S65 - Pre-commit hooks setup + commit + push (Pedro-side wrapper)
#
# Why this script: sandbox bash blocked from git commit/push and pnpm
# install on Windows-mounted filesystem. This PS script runs all the
# Pedro-side operations end-to-end.
#
# ASCII-only (S62 lesson: PS .ps1 default cp1252 fails with accented
# chars). All strings in English.
#
# Bypass during emergency: $env:HUSKY = "0"; git commit ...
# ====================================================================

$ErrorActionPreference = "Stop"
$repo = "C:\Users\pedro\Dev\PROJETO SAAS IA OFICIAL"
Set-Location $repo

Write-Host ""
Write-Host "===== S65 pre-commit setup =====" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: clean any stuck git lock (lesson S62/S63) ---
Write-Host "[1/9] Clearing git locks if present..." -ForegroundColor Yellow
$gitLock = Join-Path $repo ".git\index.lock"
if (Test-Path $gitLock) {
    Remove-Item -Force $gitLock -ErrorAction SilentlyContinue
    Write-Host "      .git/index.lock removed"
} else {
    Write-Host "      no lock"
}

# --- Step 2: restore S64 leftover modified files (corrupted by Windows file watcher) ---
Write-Host "[2/9] Restoring S64 leftover modified files..." -ForegroundColor Yellow
$leftovers = @(
    "apps/backend/test/unit/api-key.guard.spec.ts",
    "scripts/s63-fetch-fail.ps1",
    "scripts/s64a-add-apikey-spec.ps1",
    "scripts/s64a-amend-fix.ps1"
)
foreach ($f in $leftovers) {
    if (git diff --name-only -- $f) {
        Write-Host "      restoring: $f"
        git checkout HEAD -- $f
    }
}

# --- Step 3: clean S64 untracked artifacts ---
Write-Host "[3/9] Cleaning S64 untracked artifacts..." -ForegroundColor Yellow
$artifacts = @(
    "coverage-artifact-*",
    "coverage-per-path-*.json"
)
foreach ($pattern in $artifacts) {
    Get-ChildItem -Path $repo -Filter $pattern -Force -ErrorAction SilentlyContinue | ForEach-Object {
        Write-Host "      removing: $($_.Name)"
        Remove-Item -Recurse -Force $_.FullName -ErrorAction SilentlyContinue
    }
}

# --- Step 4: pnpm install (activates husky via prepare script) ---
Write-Host "[4/9] Running pnpm install..." -ForegroundColor Yellow
pnpm install
if ($LASTEXITCODE -ne 0) {
    throw "pnpm install failed (exit $LASTEXITCODE)"
}

# --- Step 5: verify husky activation ---
Write-Host "[5/9] Verifying husky activation..." -ForegroundColor Yellow
$huskyDir = Join-Path $repo ".husky\_"
if (-not (Test-Path $huskyDir)) {
    Write-Host "      .husky/_/ not auto-generated by prepare; running husky CLI..."
    pnpm exec husky
    if ($LASTEXITCODE -ne 0) { throw "husky CLI failed" }
}
if (Test-Path $huskyDir) {
    Write-Host "      OK: .husky/_/ exists"
} else {
    throw "husky activation failed"
}

# --- Step 6: smoke-test custom guards (no staged files) ---
Write-Host "[6/9] Smoke-testing custom guards..." -ForegroundColor Yellow
node scripts/git-hooks/check-windows-garbage.js
if ($LASTEXITCODE -ne 0) { throw "check-windows-garbage.js exited non-zero on clean repo" }
node scripts/git-hooks/check-secrets.js
if ($LASTEXITCODE -ne 0) { throw "check-secrets.js exited non-zero on clean repo" }
Write-Host "      OK: both guards pass on clean staging area"

# --- Step 7: stage S65 changes ---
Write-Host "[7/9] Staging changes..." -ForegroundColor Yellow
$filesToAdd = @(
    "CLAUDE.md",
    "PROJECT_HISTORY.md",
    "package.json",
    "pnpm-lock.yaml",
    ".husky/pre-commit",
    ".prettierrc",
    ".prettierignore",
    "scripts/git-hooks/check-windows-garbage.js",
    "scripts/git-hooks/check-secrets.js",
    "docs/operations/s65/PRE_COMMIT_HOOKS.md",
    "scripts/s65-pre-commit-setup.ps1"
)
foreach ($f in $filesToAdd) {
    if (Test-Path $f) {
        git add -- $f
    }
}

git status --short

# --- Step 8: commit (use -F to avoid PS heredoc with embedded quotes) ---
Write-Host "[8/9] Writing commit message and committing..." -ForegroundColor Yellow
$msgFile = Join-Path $env:TEMP "s65-commit-msg.txt"

$msg = @'
feat(s65): pre-commit hooks (husky + lint-staged + custom guards)

Diagnosis: 50%+ of CI round-trips in S60a-S64 (8+ iterations) were
preventable locally. Causes: Edit tool truncation (4x), Windows garbage
tracked (1x), Stripe-pattern test fixtures triggering GitHub push
protection (1x), malformed YAML/JSON (1x).

Stack:
- husky 9.1.7 + lint-staged 15.2.10
- 2 custom Node guards (no external deps)

Pipeline (.husky/pre-commit):
1. node scripts/git-hooks/check-windows-garbage.js  HARD FAIL
2. node scripts/git-hooks/check-secrets.js          HARD FAIL
3. npx --no-install lint-staged                     auto-fix prettier

Guards:
- check-windows-garbage.js: Novo*.txt, New File*, Untitled*,
  .DS_Store, Thumbs.db, desktop.ini, MS Office locks, swap files,
  0-byte (allowlist .gitkeep/.keep)
- check-secrets.js: 13 ERROR patterns (Stripe live/test/restricted/
  webhook, Clerk, OpenAI legacy+project, Anthropic, AWS AKIA, GitHub
  PAT/ghs, npm, Slack bot/user) + 2 WARNING (Twilio, hex), allowlist
  line-level (// pre-commit-allow-secret, test-fixture-, mock-,
  fake-, REDACTED, etc.) and path-level (__fixtures__, __mocks__)

Bypass: HUSKY=0 git commit ...

Adhoc validation passed:
- 4/4 garbage patterns blocked, real source path passed
- 5/5 secret patterns: Stripe live HIT, OpenAI legacy + project
  format both HIT after regex fix sk-(?:proj-)?[A-Za-z0-9_-]{32,},
  allowlisted test-fixture- pass, placeholder pass

Files:
  .husky/pre-commit                          NEW 1.0KB
  .prettierrc                                NEW root canonical
  .prettierignore                            NEW ~30 entries
  scripts/git-hooks/check-windows-garbage.js NEW 3.4KB
  scripts/git-hooks/check-secrets.js         NEW 6.8KB
  docs/operations/s65/PRE_COMMIT_HOOKS.md    NEW 6KB
  package.json                               +husky +lint-staged +prepare +config
  CLAUDE.md                                  +S65 row +checklist +v5.6
  PROJECT_HISTORY.md                         +S65 entry

Lessons reinforced:
- Edit tool unsafe for JSON: used python3 json.load+dump
- Bash heredoc with EOF collisions: used python3 multi-file write
- PS heredoc embedded quotes: using -F file
- Husky v9 syntax: no shebang loader

Previous: S64-C c00ae5a
'@

[System.IO.File]::WriteAllText($msgFile, $msg, [System.Text.UTF8Encoding]::new($false))
Write-Host "      msg file: $msgFile"

git commit -F $msgFile
if ($LASTEXITCODE -ne 0) { throw "git commit failed (exit $LASTEXITCODE)" }

# --- Step 9: push ---
Write-Host "[9/9] Pushing to origin/main..." -ForegroundColor Yellow
git push origin main
if ($LASTEXITCODE -ne 0) { throw "git push failed (exit $LASTEXITCODE)" }

Write-Host ""
Write-Host "===== S65 DONE =====" -ForegroundColor Green
Write-Host ""
git log --oneline -3
Write-Host ""
Write-Host "Watch CI: https://github.com/pedro-leme-perin/saas-ai-sales-assistant/actions"
